import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export interface DashboardData {
  kpis: {
    totalIssues: string;
    resolutionRate: string;
    avgResponseTime: string;
    activeCitizens: string;
  };
  issueTrends: Array<{
    month: string;
    reported: number;
    resolved: number;
  }>;
  categoryData: Array<{
    name: string;
    value: number;
  }>;
  statusData: Array<{
    name: string;
    value: number;
  }>;
  topContributors: Array<{
    name: string;
    points: number;
    issues: number;
    rank: number;
  }>;
  recentActivity: Array<{
    type: string;
    title: string;
    time: string;
    points: number;
  }>;
}

export const generateDashboardPDF = async (data: DashboardData, t: (key: string) => string): Promise<void> => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  let currentY = margin;

  // Helper function to add text with word wrapping
  const addWrappedText = (text: string, x: number, y: number, maxWidth: number, fontSize = 12) => {
    pdf.setFontSize(fontSize);
    const lines = pdf.splitTextToSize(text, maxWidth);
    pdf.text(lines, x, y);
    return y + (lines.length * fontSize * 0.4);
  };

  // Helper function to check if we need a new page
  const checkNewPage = (requiredHeight: number) => {
    if (currentY + requiredHeight > pageHeight - margin) {
      pdf.addPage();
      currentY = margin;
    }
  };

  // Title
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text('SAARTHI Dashboard Report', margin, currentY);
  currentY += 15;

  // Date
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, margin, currentY);
  currentY += 10;

  // KPI Section
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Key Performance Indicators', margin, currentY);
  currentY += 10;

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  const kpiData = [
    { label: 'Total Issues', value: data.kpis.totalIssues },
    { label: 'Resolution Rate', value: data.kpis.resolutionRate },
    { label: 'Average Response Time', value: data.kpis.avgResponseTime },
    { label: 'Active Citizens', value: data.kpis.activeCitizens }
  ];

  kpiData.forEach(kpi => {
    checkNewPage(8);
    pdf.text(`${kpi.label}: ${kpi.value}`, margin, currentY);
    currentY += 8;
  });

  currentY += 10;

  // Issue Trends
  checkNewPage(20);
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Monthly Issue Trends', margin, currentY);
  currentY += 10;

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  data.issueTrends.forEach(trend => {
    checkNewPage(8);
    pdf.text(`${trend.month}: Reported - ${trend.reported}, Resolved - ${trend.resolved}`, margin, currentY);
    currentY += 8;
  });

  currentY += 10;

  // Categories
  checkNewPage(20);
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Issues by Category', margin, currentY);
  currentY += 10;

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  data.categoryData.forEach(category => {
    checkNewPage(8);
    pdf.text(`${category.name}: ${category.value}%`, margin, currentY);
    currentY += 8;
  });

  currentY += 10;

  // Status Overview
  checkNewPage(20);
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Issue Status Overview', margin, currentY);
  currentY += 10;

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  data.statusData.forEach(status => {
    checkNewPage(8);
    pdf.text(`${status.name}: ${status.value}%`, margin, currentY);
    currentY += 8;
  });

  currentY += 10;

  // Top Contributors
  checkNewPage(20);
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Top Contributors', margin, currentY);
  currentY += 10;

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  data.topContributors.forEach(contributor => {
    checkNewPage(8);
    pdf.text(`${contributor.rank}. ${contributor.name} - ${contributor.points} points, ${contributor.issues} issues`, margin, currentY);
    currentY += 8;
  });

  currentY += 10;

  // Recent Activity
  checkNewPage(20);
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Recent Activity', margin, currentY);
  currentY += 10;

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  data.recentActivity.forEach(activity => {
    checkNewPage(8);
    pdf.text(`${activity.title} (${activity.time}) - +${activity.points} points`, margin, currentY);
    currentY += 8;
  });

  // Footer
  const footerY = pageHeight - 15;
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'italic');
  pdf.text('Generated by SAARTHI - Empowering Communities Through Technology', pageWidth / 2, footerY, { align: 'center' });

  // Save the PDF
  pdf.save(`saarthi-dashboard-report-${new Date().toISOString().split('T')[0]}.pdf`);
};

export const generateDashboardPDFWithCharts = async (
  dashboardElement: HTMLElement,
  data: DashboardData,
  t: (key: string) => string
): Promise<void> => {
  const tTyped = (key: string) => t(key) as string;
  try {
    // Generate canvas from the dashboard element
    const canvas = await html2canvas(dashboardElement, {
      scale: 2,
      useCORS: true,
      allowTaint: true,
      backgroundColor: '#ffffff',
      width: dashboardElement.scrollWidth,
      height: dashboardElement.scrollHeight,
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');

    // Calculate dimensions to fit the canvas in the PDF
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = pdf.internal.pageSize.getHeight();
    const imgWidth = pdfWidth - 20; // 10mm margin on each side
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    let heightLeft = imgHeight;
    let position = 10; // Start 10mm from top

    // Add the first page
    pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight);
    heightLeft -= pdfHeight - 20; // Subtract the space used on the first page

    // Add additional pages if needed
    while (heightLeft > 0) {
      position = heightLeft - imgHeight + 10; // Adjust position for next page
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight);
      heightLeft -= pdfHeight - 20;
    }

    // Add header and footer to all pages
    const totalPages = (pdf as unknown as { internal: { pages: unknown[] } }).internal.pages.length - 1;
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);

      // Header
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text('SAARTHI Dashboard Report', 10, 10);

      // Footer
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Page ${i} of ${totalPages}`, pdfWidth / 2, pdfHeight - 10, { align: 'center' });
      pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, 10, pdfHeight - 10);
    }

    pdf.save(`saarthi-dashboard-report-${new Date().toISOString().split('T')[0]}.pdf`);
  } catch (error) {
    console.error('Error generating PDF with charts:', error);
    // Fallback to text-only PDF
    await generateDashboardPDF(data, t);
  }
};
